

#阿里云OSS
aliyunoss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI9kgRRh2eU3Cd
  accessKeySecret: u58apwTfGPSYmVXuVAYWawmkT7eS5K
  bucketNameHeader: hooviewheader
  bucketNameBanner: hooviewbanner
  bucketLaunchlive: hooviewlaunchlive
#短信

#微信

#redis
redis:
  addr_array: localhost
  auth: hooview666
  max_active: 8
  max_idle: 8
  max_wait: 10000
  timeout: 10000

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://hooview:hooview123@localhost:8660/eureka/
